# Generated by Django 5.1.4 on 2026-04-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_rejoindre",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("statut", models.CharField(max_length=20)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("tour_actuel", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categorie", models.CharField(max_length=50)),
                ("type_question", models.CharField(max_length=20)),
                (
                    "type_reponse",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("texte_question", models.TextField()),
                ("bonne_reponse", models.TextField()),
                ("mauvaise_prop_1", models.TextField(blank=True, null=True)),
                ("mauvaise_prop_2", models.TextField(blank=True, null=True)),
                ("mauvaise_prop_3", models.TextField(blank=True, null=True)),
                ("synonymes_acceptes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudo", models.CharField(max_length=50, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
                ("role", models.CharField(default="ROLE_USER", max_length=20)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartieJoueur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_ia", models.BooleanField(default=False)),
                ("nom_ia", models.CharField(blank=True, max_length=50, null=True)),
                ("position_plateau", models.IntegerField(default=0)),
                ("ordre_tour", models.IntegerField(default=0)),
                ("effet_actif", models.CharField(default="AUCUN", max_length=50)),
                ("duree_effet", models.IntegerField(default=0)),
                (
                    "partie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joueurs",
                        to="game.partie",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="partie",
            name="questions_posees",
            field=models.ManyToManyField(blank=True, to="game.question"),
        ),
        migrations.AddField(
            model_name="partie",
            name="createur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties_creees",
                to="game.utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="partie",
            name="vainqueur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parties_gagnees",
                to="game.utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="HistoriqueQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categorie", models.CharField(max_length=50)),
                (
                    "partie_joueur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques_bot",
                        to="game.partiejoueur",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.question"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="game.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasePlateau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_plateau", models.IntegerField()),
                ("effet", models.CharField(default="AUCUN", max_length=50)),
                ("categorie", models.CharField(blank=True, max_length=50, null=True)),
                ("points", models.IntegerField(default=0)),
                (
                    "partie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases_plateau",
                        to="game.partie",
                    ),
                ),
            ],
            options={
                "ordering": ["position_plateau"],
                "unique_together": {("partie", "position_plateau")},
            },
        ),
    ]
