spring.application.name=backspring

# 1. Configuration H2 en mode Fichier (Persistant)
spring.datasource.url=jdbc:h2:file:./jeu_plateau_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 2. Comportement de création des tables
spring.jpa.hibernate.ddl-auto=update

# 3. Activation de la console d'administration web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# 4. URL de l'API Python (Indispensable pour que Spring puisse parler à l'IA)
python.api.url=https://elgronaldo-plateau.hf.space

# 5. Inclusion du fichier contenant les vraies clés (application-secret.properties)
spring.profiles.include=secret